# AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-6c091069ce6d4bda9951b55b505e579d
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
      strict-json-schema: true
      max-token: 8192
      response-format: json_object

    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-b4ec29e4b66c4ba4815254b3a0cbb5df
      model-name: deepseek-chat
      max-tokens: 8192
      log-requests: true
      log-responses: true


